### ISSUE TITLE
11

### ISSUE THREAD

**Issue by Ingvarr71** [h0sch180/nougat_platform_manifest#1]
Hello! Error downloading source codes CrDroid 3.8.9 REBORN.

fatal: is not a git repository: "/home/iodine71/crd/.repo/projects/external/fio.git"

Checking out projects: 17% (103/581) LineageOS / android_external_ffmpegerror: Cannot checkout platform / external / fio: ManifestInvalidRevisionError: revision refs / tags / android-7.1.2_r36 in platform / external / fio not found

error: in `sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --force-sync -j8`: revision refs / tags / android-7.1.2_r36 in platform / external / fio not found

**Comment by h0sch180** [comment]
Hi
Use the right sync command, then it should Work.
repo init -u https://github.com/h0sch180/nougat_platform_manifest.git -b nougat-crdroid

repo sync -f --force-sync --no-clone-bundle

**Comment by Ingvarr71** [comment]
Thanks!!!!
